### ISSUE TITLE
Code needs documentation

### ISSUE THREAD

**Issue by luisortizuriarte** [desmond-gray/Assignment_3#2]
As you write your code, keep in mind to document what you are doing. This will help other people (like me!) understand what you are doing and how to offer help, and it will help future you understand what you wrote! 

Please add documentation to your code using markdown cells and inline comments so that a reader can understand your code.

**Comment by desmond-gray** [comment]
I added documentation to my code

**Comment by luisortizuriarte** [comment]
Your notebook is much easier to follow with the added documentation on Markdown cells.
