### ISSUE TITLE
Defining neutral conditions in your index

### ISSUE THREAD

**Issue by luisortizuriarte** [desmond-gray/Assignment_3#3]
In your data, you chose neutral conditions be represented when NAO = 0. However, this is a very strict requirement (the probability of NAO being a specific number is going to be very low) so you end up with very low number of neutral years. If you filtered your NAO index to include other small values like we did with ENSO, you might have a more balanced distribution.

**Comment by pdirmeyer** [comment]
I had the same question. Choosing NAO monthly; neutral as == 0 ; if you want three categories, you might choose a bounding range centered on 0.0 for neutral (e.g., ±1). Otherwise, go with two categories: positive and negative, but capturing only extreme values of NAO.

**Comment by desmond-gray** [comment]
I chose my neutral to be ±0.5

**Comment by luisortizuriarte** [comment]
Confirmed. You have narrowed your positive and negative range by adding a neutral NAO band between ±0.5.
