### ISSUE TITLE
Compositing precipitation data against precipitation?

### ISSUE THREAD

**Issue by luisortizuriarte** [desmond-gray/Assignment_3#4]
From In[14]:

`pos_nao = da_precip.where(da_precip>0)
neg_nao = da_precip.where(da_precip<0)
neutral_nao = da_precip.where(da_precip==0)`

It looks like you're using precipitation itself to composite against precipitation rather than your NAO index.

**Comment by desmond-gray** [comment]
I changed datasets from GPCP to ERA5 and was able to composite it against the NAO index

**Comment by luisortizuriarte** [comment]
You have successfully subset your precip data using the NAO index phases. Confirming issue is closed.
