### ISSUE TITLE
Tidying up after data exploration

### ISSUE THREAD

**Issue by luisortizuriarte** [desmond-gray/Assignment_3#5]
In your submitted notebook, you dedicate a lot of cells to exploratory analysis with various outputs printed out. As you work and start resolving your issues, either remove erroneous code or consolidate it into single cells with fewer printouts. This will help you avoid duplication and errors and make it easier to document as well.

**Comment by desmond-gray** [comment]
I've taken out unnecessary cells, so that only the working code remains

**Comment by luisortizuriarte** [comment]
Confirmed. Your notebook is much easier to follow now!
