### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by luisortizuriarte** [desmond-gray/Assignment_3#7]
When you attempt to plot the composite maps at the end of your assignment, you encountered an error in data formatting. We noticed that when you call the contourf method, you did not enter a longitude coordinate, which may be causing your error here.

**Comment by pdirmeyer** [comment]
Indeed, the `lat` dimension is passed to contourf, but no longitude. Needs either both or neither.

Also, the `for` loop and handling of the composites is a bit confused. As you have written it, `nao` is `comp_precip[i]` is `data` - why would you need all three?

**Comment by desmond-gray** [comment]
I initially ran into errors using 'add_cyclic_point' because of my dataset having unequal spacing between longitude coordinates, but it became resolved when I called the coordinates without it

**Comment by luisortizuriarte** [comment]
Remember, the add_cyclic_point basically "closes" our global data so that there are no gaps, a necessity when plotting data on a globe. Since your domain of interest is over the state of Virginia, you don't really need it at all! However, I would look into the [documentation for it ](https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.util.add_cyclic_point.html) as it is necessary when plotting data that represents a closed surface (ie, our data domains meet at the ends).
